INCLUDES += -I$(RIOTCPU)/msp430_common/include/

CFLAGS += -DCPU_MODEL_$(call uppercase_and_underscore,$(CPU_MODEL))

MSP430X_20BIT ?= 0
ifeq ($(MSP430X_20BIT),1)
  CFLAGS += -DMSP430X
#  CFLAGS += -mlarge -mdata-region=lower -mcode-region=upper
endif

# include the msp430 common Makefile
include $(RIOTMAKE)/arch/msp430.inc.mk
